/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;
import Repository.bayiRepository;
import Repository.bidanRepository;
import Repository.imunisasiRepository;
import entity.bayi;
import entity.bidan;
import entity.imunisasi;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import main.main;
import view.notif.Notification;
import view.panel.Data_Bidan;
import view.panel.Laporan_Pelayanan;

/**
 *
 * @author RESCOM-1
 */
public class formedit_laporanpelayanan_imunisasi extends Dialog {
    
    private int id = Laporan_Pelayanan.id;
    private int ids;
    bayiRepository bayi = new bayiRepository();
    imunisasiRepository imun = new imunisasiRepository();
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    public formedit_laporanpelayanan_imunisasi(JFrame fram) {
        super(fram);
        initComponents();
        Date apa = new Date();
        Font font = new Font("Quicksand", Font.PLAIN, 20);
        input_tgl.setFont(font);
        input_idbayi.setFont(font);
//        input_notelp.setFont(font);
        input_tgllahir.setFont(font);
        input_namaibu.setFont(font);
        input_tempatlahir.setFont(font);
        input_usia.setFont(font);
        input_jenisimunisasi.setFont(font);
        input_keterangan.setFont(font);
        input_jenisvitamin.setFont(font);
        jPanel2.setVisible(false);
        load_tabelbayi();
        input_idbayi.setText(String.valueOf(imun.get(id).getId_bayi().getId()));
        input_jenisimunisasi.setText(imun.get(id).getJenis_imunisasi());
        input_jenisvitamin.setText(imun.get(id).getJenis_vitamin());
        input_keterangan.setText(imun.get(id).getKeterangan());
        input_namaibu.setText(imun.get(id).getId_bayi().getNama_ibu());
        input_tempatlahir.setText(imun.get(id).getId_bayi().getTempat_lahir());
        input_tgllahir.setText(sdf.format(imun.get(id).getId_bayi().getTanggal_lahir()));
        input_tgl.setText(sdf.format(apa));
        input_usia.setText(String.valueOf(imun.get(id).getUsia()));
    }
    
    public void load_tabelbayi(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("nama_ibu");
        
        try {
            for(bayi apa:bayi.get()){
                model.addRow(new Object[]{
                    apa.getId(),
                    apa.getNama(),
                    apa.getTempat_lahir(),
                    apa.getTanggal_lahir(),
                    apa.getJenis_kelamin(),
                    apa.getNama_ibu()
                    
                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date1 = new view.customdate.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        btnbatal = new javax.swing.JLabel();
        input_keterangan = new javax.swing.JTextField();
        input_jenisvitamin = new javax.swing.JTextField();
        input_jenisimunisasi = new javax.swing.JTextField();
        input_usia = new javax.swing.JTextField();
        input_tgl = new javax.swing.JTextField();
        input_tempatlahir = new javax.swing.JTextField();
        input_namaibu = new javax.swing.JTextField();
        input_tgllahir = new javax.swing.JTextField();
        btcaribayi = new javax.swing.JLabel();
        input_idbayi = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        jPanel3 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setLayout(null);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit1.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editMousePressed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(810, 640, 190, 50);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbatalMousePressed(evt);
            }
        });
        jPanel1.add(btnbatal);
        btnbatal.setBounds(580, 640, 190, 60);

        input_keterangan.setBackground(new Color(0,0,0,0));
        input_keterangan.setBorder(null);
        jPanel1.add(input_keterangan);
        input_keterangan.setBounds(330, 574, 350, 30);

        input_jenisvitamin.setBackground(new Color(0,0,0,0));
        input_jenisvitamin.setBorder(null);
        jPanel1.add(input_jenisvitamin);
        input_jenisvitamin.setBounds(40, 574, 240, 30);

        input_jenisimunisasi.setBackground(new Color(0,0,0,0));
        input_jenisimunisasi.setBorder(null);
        jPanel1.add(input_jenisimunisasi);
        input_jenisimunisasi.setBounds(190, 490, 480, 30);

        input_usia.setBackground(new Color(0,0,0,0));
        input_usia.setBorder(null);
        jPanel1.add(input_usia);
        input_usia.setBounds(30, 490, 70, 30);

        input_tgl.setBackground(new Color(0,0,0,0));
        input_tgl.setBorder(null);
        input_tgl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input_tgl.setFocusable(false);
        jPanel1.add(input_tgl);
        input_tgl.setBounds(40, 410, 200, 30);

        input_tempatlahir.setBackground(new Color(0,0,0,0));
        input_tempatlahir.setBorder(null);
        input_tempatlahir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input_tempatlahir.setFocusable(false);
        jPanel1.add(input_tempatlahir);
        input_tempatlahir.setBounds(40, 240, 370, 30);

        input_namaibu.setBackground(new Color(0,0,0,0));
        input_namaibu.setBorder(null);
        input_namaibu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input_namaibu.setFocusable(false);
        jPanel1.add(input_namaibu);
        input_namaibu.setBounds(570, 160, 370, 30);

        input_tgllahir.setBackground(new Color(0,0,0,0));
        input_tgllahir.setBorder(null);
        input_tgllahir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input_tgllahir.setFocusable(false);
        jPanel1.add(input_tgllahir);
        input_tgllahir.setBounds(40, 325, 410, 30);

        btcaribayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_caribayi1.png"))); // NOI18N
        btcaribayi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcaribayiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btcaribayiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btcaribayiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btcaribayiMousePressed(evt);
            }
        });
        jPanel1.add(btcaribayi);
        btcaribayi.setBounds(370, 150, 100, 50);

        input_idbayi.setBackground(new Color(0,0,0,0));
        input_idbayi.setBorder(null);
        input_idbayi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        input_idbayi.setFocusable(false);
        jPanel1.add(input_idbayi);
        input_idbayi.setBounds(40, 160, 320, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/laporanpelayanan_imunisasi.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1040, 710);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 0, 1050, 710);

        jPanel2.setBackground(new Color(0,0,0,0));
        jPanel2.setLayout(null);

        jScrollPane1.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 1160, 370);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(890, 10, 310, 70);

        search.setBackground(new Color(0,0,0,0));
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(950, 30, 230, 30);

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/formcari_bayi.png"))); // NOI18N
        jPanel2.add(bg1);
        bg1.setBounds(6, 0, 1218, 557);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1230, 560);

        setSize(new java.awt.Dimension(1245, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
    closeMessage();
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btcaribayiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcaribayiMouseClicked
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_btcaribayiMouseClicked

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal2.png")));
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal1.png")));
    }//GEN-LAST:event_btnbatalMouseExited

    private void btnbatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMousePressed
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal3.png")));
    }//GEN-LAST:event_btnbatalMousePressed

    private void btcaribayiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcaribayiMouseEntered
    btcaribayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_caribayi2.png")));
    }//GEN-LAST:event_btcaribayiMouseEntered

    private void btcaribayiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcaribayiMouseExited
    btcaribayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_caribayi1.png")));
    }//GEN-LAST:event_btcaribayiMouseExited

    private void btcaribayiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcaribayiMousePressed
    btcaribayi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_caribayi3.png")));
    }//GEN-LAST:event_btcaribayiMousePressed

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        bayi idbayi = new bayi(Integer.valueOf(input_idbayi.getText()));
        try {
            imunisasi apa = new imunisasi(id, idbayi, sdf.parse(input_tgl.getText()),
                    Integer.valueOf(input_usia.getText()), input_jenisimunisasi.getText(),
                    input_jenisvitamin.getText(), input_keterangan.getText());
            boolean cobak = imun.update(apa);
            if(cobak) {
                main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Data Berhasil Ditambahakan");
            panel.showNotification();
            closeMessage();
            }else {
                 main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Data Gagal Ditambahakan");
            panel.showNotification();
            }
        } catch (Exception e) {
            main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Data Gagal Ditambahakan");
            panel.showNotification();
        }
        
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
    btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit2.png")));
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
    btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit1.png")));
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMousePressed
    btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit3.png")));
    }//GEN-LAST:event_btn_editMousePressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.rowAtPoint(evt.getPoint());
        String idd = table.getValueAt(baris, 0).toString();
        ids = Integer.valueOf(idd);
        input_idbayi.setText(idd);
        input_tempatlahir.setText(bayi.get(ids).getTempat_lahir());
        System.out.println(ids);
        
        try {
            
        
        input_tgllahir.setText(sdf.format(bayi.get(ids).getTanggal_lahir()));
        input_namaibu.setText(bayi.get(ids).getNama_ibu());
        
        
        
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("gagal");
        }
        if(ids != 0){
            jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        } else {
            System.out.println("pilih dulu");
        }
    }//GEN-LAST:event_tableMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
//        load_tabel(search.getText());
    }//GEN-LAST:event_searchKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel btcaribayi;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btnbatal;
    private view.customdate.DateChooser date1;
    private javax.swing.JTextField input_idbayi;
    private javax.swing.JTextField input_jenisimunisasi;
    private javax.swing.JTextField input_jenisvitamin;
    private javax.swing.JTextField input_keterangan;
    private javax.swing.JTextField input_namaibu;
    private javax.swing.JTextField input_tempatlahir;
    private javax.swing.JTextField input_tgl;
    private javax.swing.JTextField input_tgllahir;
    private javax.swing.JTextField input_usia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private view.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
