/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;
import Repository.bidanRepository;
import Repository.ibu_hamilRepository;
import entity.bidan;
import entity.ibu_hamil;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import main.main;
import view.notif.Notification;
import view.panel.Data_User;
import view.panel.Laporan_Registrasi;

/**
 *
 * @author RESCOM-1
 */
public class formedit_ibuhamil extends Dialog {
    private int id = Laporan_Registrasi.id;
    ibu_hamilRepository ibu = new ibu_hamilRepository();
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    public formedit_ibuhamil(JFrame fram) {
        super(fram);
        initComponents();
        Font font = new Font("Quicksand", Font.PLAIN, 20);
        input_nama_ibu.setFont(font);
        input_alamat.setFont(font);
        input_notelp.setFont(font);
        input_goldarah.setFont(font);
        input_tanggallahir.setFont(font);
        input_tempatlahir.setFont(font);
        input_nama_suami.setFont(font);
        input_tempat_lahir_suami.setFont(font);
        input_tgllahir_suami.setFont(font);
        try {
            String ambiltanggal = sdf.format(ibu.get(id).getTanggal_lahir());
            String ambiltanggal1 = sdf.format(ibu.get(id).getTanggal_lahir_suami());
        input_nama_ibu.setText(ibu.get(id).getNama());
        input_alamat.setText(ibu.get(id).getAlamat());
        input_notelp.setText(ibu.get(id).getNo_hp());
        input_goldarah.setText(ibu.get(id).getGol_darah());
        input_tanggallahir.setText(ambiltanggal);
        input_nama_suami.setText(ibu.get(id).getNama_suami());
        input_tempat_lahir_suami.setText(ibu.get(id).getTempat_lahir_suami());
        input_tgllahir_suami.setText(ambiltanggal1);
        input_tempatlahir.setText(ibu.get(id).getTempat_lahir());
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date1 = new view.customdate.DateChooser();
        date2 = new view.customdate.DateChooser();
        btnbatal = new javax.swing.JLabel();
        btnedit = new javax.swing.JLabel();
        input_tgllahir_suami = new javax.swing.JTextField();
        input_tempat_lahir_suami = new javax.swing.JTextField();
        input_nama_suami = new javax.swing.JTextField();
        input_notelp = new javax.swing.JTextField();
        input_tanggallahir = new javax.swing.JTextField();
        input_alamat = new javax.swing.JTextField();
        input_tempatlahir = new javax.swing.JTextField();
        input_goldarah = new javax.swing.JTextField();
        input_nama_ibu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        date1.setTextRefernce(input_tanggallahir);

        date2.setTextRefernce(input_tgllahir_suami);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbatalMousePressed(evt);
            }
        });
        getContentPane().add(btnbatal);
        btnbatal.setBounds(140, 530, 190, 60);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit1.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btneditMousePressed(evt);
            }
        });
        getContentPane().add(btnedit);
        btnedit.setBounds(390, 530, 190, 60);

        input_tgllahir_suami.setBackground(new Color(0,0,0,0));
        input_tgllahir_suami.setBorder(null);
        getContentPane().add(input_tgllahir_suami);
        input_tgllahir_suami.setBounds(230, 463, 240, 30);

        input_tempat_lahir_suami.setBackground(new Color(0,0,0,0));
        input_tempat_lahir_suami.setBorder(null);
        getContentPane().add(input_tempat_lahir_suami);
        input_tempat_lahir_suami.setBounds(390, 375, 270, 30);

        input_nama_suami.setBackground(new Color(0,0,0,0));
        input_nama_suami.setBorder(null);
        getContentPane().add(input_nama_suami);
        input_nama_suami.setBounds(40, 379, 270, 30);

        input_notelp.setBackground(new Color(0,0,0,0));
        input_notelp.setBorder(null);
        getContentPane().add(input_notelp);
        input_notelp.setBounds(390, 295, 270, 30);

        input_tanggallahir.setBackground(new Color(0,0,0,0));
        input_tanggallahir.setBorder(null);
        getContentPane().add(input_tanggallahir);
        input_tanggallahir.setBounds(30, 295, 240, 30);

        input_alamat.setBackground(new Color(0,0,0,0));
        input_alamat.setBorder(null);
        input_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(input_alamat);
        input_alamat.setBounds(390, 217, 270, 30);

        input_tempatlahir.setBackground(new Color(0,0,0,0));
        input_tempatlahir.setBorder(null);
        getContentPane().add(input_tempatlahir);
        input_tempatlahir.setBounds(30, 217, 290, 30);

        input_goldarah.setBackground(new Color(0,0,0,0));
        input_goldarah.setBorder(null);
        input_goldarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_goldarahActionPerformed(evt);
            }
        });
        getContentPane().add(input_goldarah);
        input_goldarah.setBounds(380, 135, 280, 30);

        input_nama_ibu.setBackground(new Color(0,0,0,0));
        input_nama_ibu.setBorder(null);
        input_nama_ibu.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(input_nama_ibu);
        input_nama_ibu.setBounds(30, 132, 280, 30);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 295, 40, 30);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 463, 40, 32);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/formedit_ibuhamil.png"))); // NOI18N
        bg.setText("...");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 690, 610);

        setSize(new java.awt.Dimension(705, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
    closeMessage();
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        
        try {
            Date ambil1 = sdf.parse(input_tanggallahir.getText());
            Date ambil2 = sdf.parse(input_tgllahir_suami.getText());
            
            ibu_hamil ibu1 = new ibu_hamil(id,input_nama_ibu.getText(),input_tempatlahir.getText(),
                    ambil1,input_goldarah.getText(),input_alamat.getText(),
                    input_notelp.getText(),input_nama_suami.getText(),
            input_tempat_lahir_suami.getText(),ambil2);
            boolean cobak = ibu.update(ibu1);
            if (cobak){
                main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.SUCCESS, Notification.Location.BOTTOM_RIGHT, "Data Berhasil Ditambahakan");
            panel.showNotification();
            closeMessage();
            } else{
                main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Data Gagal Ditambahakan");
            panel.showNotification();
            }
            
        } catch (Exception e) {
            main main =(main)SwingUtilities.getWindowAncestor(this);
            Notification panel = new Notification(main, Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Data Gagal Ditambahakan");
            panel.showNotification();
        }
        
    }//GEN-LAST:event_btneditMouseClicked

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal2.png")));
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal1.png")));
    }//GEN-LAST:event_btnbatalMouseExited

    private void btnbatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMousePressed
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformbatal3.png")));
    }//GEN-LAST:event_btnbatalMousePressed

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit2.png")));
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit1.png")));
    }//GEN-LAST:event_btneditMouseExited

    private void btneditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMousePressed
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnformedit3.png")));
    }//GEN-LAST:event_btneditMousePressed

    private void input_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_alamatActionPerformed

    private void input_goldarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_goldarahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_goldarahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    date1.showPopup();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    date2.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnedit;
    private view.customdate.DateChooser date1;
    private view.customdate.DateChooser date2;
    private javax.swing.JTextField input_alamat;
    private javax.swing.JTextField input_goldarah;
    private javax.swing.JTextField input_nama_ibu;
    private javax.swing.JTextField input_nama_suami;
    private javax.swing.JTextField input_notelp;
    private javax.swing.JTextField input_tanggallahir;
    private javax.swing.JTextField input_tempat_lahir_suami;
    private javax.swing.JTextField input_tempatlahir;
    private javax.swing.JTextField input_tgllahir_suami;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
