/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import main.main;

public class validasiberhasil1 extends Dialog {
    private int aaa;
    
    /**
     * Creates new form validasiberhasil
     */
    public validasiberhasil1(JFrame fram, String pindahnyakemana) {
        super(fram);
        initComponents();
        Font font = new Font("Quicksand", Font.BOLD, 30);
        txt_peringatan.setFont(font);
        txt_peringatan.setHorizontalAlignment(SwingConstants.CENTER);
        txt_peringatan.setText(pindahnyakemana);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_peringatan = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(0,0,0,95));
        getContentPane().setLayout(null);
        getContentPane().add(txt_peringatan);
        txt_peringatan.setBounds(430, 400, 500, 50);

        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnya1.png"))); // NOI18N
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        getContentPane().add(button);
        button.setBounds(620, 490, 120, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/ValidasiBerhasil.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(400, 220, 570, 340);

        setSize(new java.awt.Dimension(1482, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
    
    closeMessage();
    
    }//GEN-LAST:event_buttonMouseClicked

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnya2.png")));
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnya1.png")));
    }//GEN-LAST:event_buttonMouseExited

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnya3.png")));
    }//GEN-LAST:event_buttonMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel button;
    private javax.swing.JLabel txt_peringatan;
    // End of variables declaration//GEN-END:variables
}
