/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

/**
 *
 * @author RESCOM-1
 */
public class Data_Kader extends javax.swing.JPanel {

    /**
     * Creates new form Data_Kader
     */
    public Data_Kader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_form = new javax.swing.JLabel();
        panelShadow25 = new view.swing.panelcustom.PanelShadow();
        jScrollPane25 = new javax.swing.JScrollPane();
        table25 = new view.swing.Table();

        setBackground(new java.awt.Color(246, 246, 233));

        txt_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/txt_Form Data Kader.png"))); // NOI18N

        panelShadow25.setBackground(new java.awt.Color(234, 245, 255));

        jScrollPane25.setBorder(null);

        table25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane25.setViewportView(table25);

        javax.swing.GroupLayout panelShadow25Layout = new javax.swing.GroupLayout(panelShadow25);
        panelShadow25.setLayout(panelShadow25Layout);
        panelShadow25Layout.setHorizontalGroup(
            panelShadow25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow25Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        panelShadow25Layout.setVerticalGroup(
            panelShadow25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow25Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelShadow25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_form)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_form, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(panelShadow25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private view.swing.panelcustom.PanelShadow panelShadow1;
    private view.swing.panelcustom.PanelShadow panelShadow10;
    private view.swing.panelcustom.PanelShadow panelShadow11;
    private view.swing.panelcustom.PanelShadow panelShadow12;
    private view.swing.panelcustom.PanelShadow panelShadow13;
    private view.swing.panelcustom.PanelShadow panelShadow14;
    private view.swing.panelcustom.PanelShadow panelShadow15;
    private view.swing.panelcustom.PanelShadow panelShadow16;
    private view.swing.panelcustom.PanelShadow panelShadow17;
    private view.swing.panelcustom.PanelShadow panelShadow18;
    private view.swing.panelcustom.PanelShadow panelShadow19;
    private view.swing.panelcustom.PanelShadow panelShadow2;
    private view.swing.panelcustom.PanelShadow panelShadow20;
    private view.swing.panelcustom.PanelShadow panelShadow21;
    private view.swing.panelcustom.PanelShadow panelShadow22;
    private view.swing.panelcustom.PanelShadow panelShadow23;
    private view.swing.panelcustom.PanelShadow panelShadow24;
    private view.swing.panelcustom.PanelShadow panelShadow25;
    private view.swing.panelcustom.PanelShadow panelShadow5;
    private view.swing.panelcustom.PanelShadow panelShadow6;
    private view.swing.panelcustom.PanelShadow panelShadow7;
    private view.swing.panelcustom.PanelShadow panelShadow8;
    private view.swing.panelcustom.PanelShadow panelShadow9;
    private view.swing.Table table1;
    private view.swing.Table table10;
    private view.swing.Table table11;
    private view.swing.Table table12;
    private view.swing.Table table13;
    private view.swing.Table table14;
    private view.swing.Table table15;
    private view.swing.Table table16;
    private view.swing.Table table17;
    private view.swing.Table table18;
    private view.swing.Table table19;
    private view.swing.Table table2;
    private view.swing.Table table20;
    private view.swing.Table table21;
    private view.swing.Table table22;
    private view.swing.Table table23;
    private view.swing.Table table24;
    private view.swing.Table table25;
    private view.swing.Table table5;
    private view.swing.Table table6;
    private view.swing.Table table7;
    private view.swing.Table table8;
    private view.swing.Table table9;
    private javax.swing.JLabel txt_form;
    // End of variables declaration//GEN-END:variables
}
